import { toPng } from 'html-to-image';
import { jsPDF } from 'jspdf';

export const exportMessageToPdf = async (elementId: string, currentMode: string) => {
  const element = document.getElementById(elementId);
  if (!element) return;

  try {
    const clone = element.cloneNode(true) as HTMLElement;
    const computedStyles = window.getComputedStyle(document.body);
    const bgColor = computedStyles.backgroundColor || '#E4E3E0';
    const textColor = computedStyles.color || '#141414';
    
    // Explicitly inline children colors to ensure html-to-image paints accurately
    // and copies the computed styles exactly matching the current theme/dark mode.
    const originalNodes = element.querySelectorAll('*');
    const clonedNodes = clone.querySelectorAll('*');
    for (let i = 0; i < originalNodes.length; i++) {
        const origNode = originalNodes[i] as HTMLElement;
        const clonedNode = clonedNodes[i] as HTMLElement;
        const computed = window.getComputedStyle(origNode);
        
        clonedNode.style.color = computed.color;
        if (computed.backgroundColor && computed.backgroundColor !== 'rgba(0, 0, 0, 0)') {
            clonedNode.style.backgroundColor = computed.backgroundColor;
        }
        if (computed.borderColor && computed.borderColor !== 'rgba(0, 0, 0, 0)' && computed.borderColor !== 'rgb(0, 0, 0)') {
            clonedNode.style.borderColor = computed.borderColor;
        }
    }

    const wrapper = document.createElement('div');
    wrapper.style.padding = '40px';
    wrapper.style.backgroundColor = bgColor;
    wrapper.style.width = '800px';
    wrapper.style.color = textColor;
    wrapper.style.fontFamily = 'var(--font-sans)';
    
    const header = document.createElement('div');
    header.innerHTML = `
      <div style="border-bottom: 2px solid ${textColor}; padding-bottom: 16px; margin-bottom: 32px; display: flex; justify-content: space-between; align-items: flex-end;">
        <div>
          <h1 style="font-size: 24px; font-weight: bold; color: ${textColor}; margin: 0; font-family: var(--font-sans); letter-spacing: -0.025em;">Liberica Assistance</h1>
          <p style="font-size: 12px; font-weight: bold; color: ${textColor}; margin: 4px 0 0 0; text-transform: uppercase; letter-spacing: 1px; font-family: var(--font-mono);">Percepat Langkah, Tumbuh Bersama Ide Anda. • ${currentMode.toUpperCase()}</p>
        </div>
        <div style="font-size: 12px; color: ${textColor}; font-weight: 500; font-family: var(--font-mono);">
          Generated on ${new Date().toLocaleDateString('id-ID')}
        </div>
      </div>
    `;
    wrapper.appendChild(header);
    wrapper.appendChild(clone);
    
    const footer = document.createElement('div');
    footer.innerHTML = `
      <div style="border-top: 1px solid ${textColor}; padding-top: 16px; margin-top: 40px; text-align: center; font-size: 10px; color: ${textColor}; font-family: var(--font-mono);">
        CONFIDENTIAL AND PROPRIETARY • GENERATED BY LIBERICA ASSISTANCE
      </div>
    `;
    wrapper.appendChild(footer);
    
    const container = document.createElement('div');
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    container.style.top = '-9999px';
    container.appendChild(wrapper);
    document.body.appendChild(container);
    
    // Let DOM flush so that everything is rendered properly before capture
    await new Promise(r => setTimeout(r, 200));
    
    const dataUrl = await toPng(wrapper, {
      pixelRatio: 2,
      backgroundColor: bgColor,
      skipFonts: true,
      imagePlaceholder: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
      filter: (node) => {
        if (!node || typeof node.tagName !== 'string') return true;
        const tag = node.tagName.toLowerCase();
        return tag !== 'iframe' && tag !== 'script' && tag !== 'noscript';
      },
      style: {
        transform: 'scale(1)',
        transformOrigin: 'top left'
      }
    });
    
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });
    
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();
    
    const imgProps = pdf.getImageProperties(dataUrl);
    
    // Scale image to fit the width of A4
    const imgWidth = pdfWidth;
    const imgHeight = (imgProps.height * pdfWidth) / imgProps.width;

    let heightLeft = imgHeight;
    let position = 0;

    // Add first page
    pdf.addImage(dataUrl, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pdfHeight;

    // Add subsequent pages if the content is taller than one A4 page
    while (heightLeft > 0) {
      position -= pdfHeight; // shift image up by one page height
      pdf.addPage();
      pdf.addImage(dataUrl, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pdfHeight;
    }

    pdf.save(`Liberica_${currentMode}_${Date.now()}.pdf`);
    
    document.body.removeChild(container);
  } catch (err) {
    console.error('Failed to generate PDF', err);
    alert('Failed to generate PDF. Please try again.');
    // Clean up container if it was left behind
    const container = document.body.lastChild;
    if (container && (container as HTMLElement).style.left === '-9999px') {
      document.body.removeChild(container);
    }
  }
};
