import html2pdf from 'html2pdf.js';

export const exportMessageToPdf = async (elementId: string, currentMode: string) => {
  const element = document.getElementById(elementId);
  if (!element) return;

  try {
    const clone = element.cloneNode(true) as HTMLElement;
    const wrapper = document.createElement('div');
    wrapper.style.padding = '40px';
    wrapper.style.backgroundColor = '#E4E3E0';
    wrapper.style.width = '800px';
    wrapper.style.color = '#141414';
    wrapper.style.fontFamily = 'Helvetica Neue, Helvetica, Arial, sans-serif';
    
    const header = document.createElement('div');
    header.innerHTML = `
      <div style="border-bottom: 2px solid #141414; padding-bottom: 16px; margin-bottom: 32px; display: flex; justify-content: space-between; align-items: flex-end;">
        <div>
          <h1 style="font-size: 24px; font-weight: bold; color: #141414; margin: 0; font-family: Georgia, serif; font-style: italic;">Liberica Assistance</h1>
          <p style="font-size: 12px; font-weight: bold; color: #141414; margin: 4px 0 0 0; text-transform: uppercase; letter-spacing: 1px; font-family: Courier, monospace;">Percepat Langkah, Tumbuh Bersama Ide Anda. • ${currentMode.toUpperCase()}</p>
        </div>
        <div style="font-size: 12px; color: #141414; font-weight: 500; font-family: Courier, monospace;">
          Generated on ${new Date().toLocaleDateString('id-ID')}
        </div>
      </div>
    `;
    wrapper.appendChild(header);
    wrapper.appendChild(clone);
    
    const footer = document.createElement('div');
    footer.innerHTML = `
      <div style="border-top: 1px solid #141414; padding-top: 16px; margin-top: 40px; text-align: center; font-size: 10px; color: #141414; font-family: Courier, monospace;">
        CONFIDENTIAL AND PROPRIETARY • GENERATED BY LIBERICA ASSISTANCE
      </div>
    `;
    wrapper.appendChild(footer);
    
    const container = document.createElement('div');
    container.style.position = 'absolute';
    container.style.left = '0';
    container.style.top = '0';
    container.style.overflow = 'hidden';
    container.style.height = '0';
    container.style.width = '100%';
    container.style.zIndex = '-9999';
    container.appendChild(wrapper);
    document.body.appendChild(container);
    
    const opt: any = {
      margin:       [20, 15, 20, 15],
      filename:     `Liberica_${currentMode}_${Date.now()}.pdf`,
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { scale: 2, useCORS: true, backgroundColor: '#E4E3E0', windowWidth: 800 },
      jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak:    { mode: ['css', 'legacy'], avoid: ['.bento-card', 'li', 'h1', 'h2', 'h3'] }
    };
    
    await html2pdf().set(opt).from(wrapper).save();
    document.body.removeChild(container);
  } catch (err) {
    console.error('Failed to generate PDF', err);
    alert('Failed to generate PDF. Please try again.');
  }
};
